services:
  - type: web
    name: flask-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.server:app
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      # add DB creds here or in the dashboard as “Secret Files/Env Vars”
      # - key: SUPABASE_URL
      #   sync: false
      # - key: SUPABASE_KEY
      #   sync: false

  # Cron runs twice (UTC) to cover DST; your job can be idempotent.
  - type: cron
    name: daily-08am-ny-1
    env: python
    plan: free
    schedule: "0 12 * * *"          # 12:00 UTC ~ 08:00 NY (EDT)
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.cron_entry

  - type: cron
    name: daily-08am-ny-2
    env: python
    plan: free
    schedule: "0 13 * * *"          # 13:00 UTC ~ 08:00 NY (EST)
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.cron_entry
