name: daily-db-update
on:
  schedule:
    # Run at both UTC times and let your code be idempotent,
    # or inside your code gate to 08:00 America/New_York.
    - cron: "0 12 * * *"
    - cron: "0 13 * * *"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run daily job
        # EITHER call the module runner...
        run: python -m src.cron_entry
        # ...OR call your function directly without a runner:
        # run: python -c "from src.cron import update_latest_data; update_latest_data()"

        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # add any other env your cron uses
