name: daily-db-update
on:
  schedule:
    - cron: "0 12 * * *"   # 08:00 EDT
    - cron: "0 13 * * *"   # 08:00 EST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run daily job
        run: python -m src.cron_entry
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
